
        /*
         * This is an auto-generated file which is automatically generated whenever the target is built
         */


        
#ifndef __sofi__h__
#define __sofi__h__

#include "mbed.h"

#pragma pack(push, 1)

#define SOFI_ARRAY_SIZE sizeof(sofi_struct)

typedef struct sofi_struct {
  bool mcu_hv_en;
  bool mppt_overvoltage_fault_reset;
  float speed_target;
  float energy_target;
} sofi_struct;

// Data storage structs
extern sofi_struct sofi_data;

bool get_sofi_mcu_hv_en();
void set_sofi_mcu_hv_en(bool val);

bool get_sofi_mppt_overvoltage_fault_reset();
void set_sofi_mppt_overvoltage_fault_reset(bool val);

float get_sofi_speed_target();
void set_sofi_speed_target(float val);

float get_sofi_energy_target();
void set_sofi_energy_target(float val);
 /* Autogenerated Code Ends */

#pragma pack(pop)
#endif


