
        /*
         * This is an auto-generated file which is automatically generated whenever the target is built
         */


        
#include "sofi.h"
#include "dataFormat.h"

sofi_struct sofi_data;

Mutex mcu_hv_en_sofi_mutex;
Mutex mppt_overvoltage_fault_reset_sofi_mutex;
Mutex speed_target_sofi_mutex;
Mutex energy_target_sofi_mutex;

bool get_sofi_mcu_hv_en() {
  mcu_hv_en_sofi_mutex.lock();
  bool val = sofi_data.mcu_hv_en;
  mcu_hv_en_sofi_mutex.unlock();
  return val;
}
void set_sofi_mcu_hv_en(bool val) {
  mcu_hv_en_sofi_mutex.lock();
  sofi_data.mcu_hv_en = val;
  set_mcu_hv_en(val);
  mcu_hv_en_sofi_mutex.unlock();
}

bool get_sofi_mppt_overvoltage_fault_reset() {
  mppt_overvoltage_fault_reset_sofi_mutex.lock();
  bool val = sofi_data.mppt_overvoltage_fault_reset;
  mppt_overvoltage_fault_reset_sofi_mutex.unlock();
  return val;
}
void set_sofi_mppt_overvoltage_fault_reset(bool val) {
  mppt_overvoltage_fault_reset_sofi_mutex.lock();
  sofi_data.mppt_overvoltage_fault_reset = val;
  mppt_overvoltage_fault_reset_sofi_mutex.unlock();
}

float get_sofi_speed_target() {
  speed_target_sofi_mutex.lock();
  float val = sofi_data.speed_target;
  speed_target_sofi_mutex.unlock();
  return val;
}
void set_sofi_speed_target(float val) {
  speed_target_sofi_mutex.lock();
  sofi_data.speed_target = val;
  speed_target_sofi_mutex.unlock();
}

float get_sofi_energy_target() {
  energy_target_sofi_mutex.lock();
  float val = sofi_data.energy_target;
  energy_target_sofi_mutex.unlock();
  return val;
}
void set_sofi_energy_target(float val) {
  energy_target_sofi_mutex.lock();
  sofi_data.energy_target = val;
  energy_target_sofi_mutex.unlock();
}
 /* Autogenerated Code Ends */


